export const CONTRACT_ERROR = 'CONTRACT_ERROR--|--Home'
export const LOGS_ERROR = 'LOGS_ERROR--|--Home'
export const GET_ETHEREUM = 'GET_ETHEREUM--|--Home'
export const GET_TOKENS_ALLOWED = 'GET_TOKENS_ALLOWED--|--Home'

export const SET_ETHJS = 'SET_ETHJS--|--Home'
export const SET_WALLET = 'SET_WALLET--|--Home'
export const SET_CONTRACTS = 'SET_CONTRACTS--|--Home'
export const SET_MIN_DEPOSIT = 'SET_MIN_DEPOSIT--|--Home'
export const SET_TOKENS_ALLOWED = 'SET_TOKENS_ALLOWED--|--Home'
export const GET_PROVIDER_REQUEST = 'GET_PROVIDER_REQUEST--|--Home'
export const SET_LOGS = 'SET_LOGS--|--Home'
export const POLL_LOGS_REQUEST = 'POLL_LOGS_REQUEST--|--Home'
export const SET_DECODED_LOGS = 'SET_DECODED_LOGS--|--Home'
export const NEW_ARRAY = 'NEW_ARRAY--|--Home'

export const TX_APPROVE = 'TX_APPROVE--|--Home'
export const TX_APPLY = 'TX_APPLY--|--Home'
export const TX_CHALLENGE = 'TX_CHALLENGE--|--Home'
export const TX_COMMIT_VOTE = 'TX_COMMIT_VOTE--|--Home'
export const TX_UPDATE_STATUS = 'TX_UPDATE_STATUS--|--Home'
export const TX_CHECK_TEST= 'TX_CHECK_TEST--|--Home'

export const EV_APPLICATION = 'EV_APPLICATION--|--Home'
export const EV_CHALLENGE = 'EV_CHALLENGE--|--Home'
export const EV_TRANSFER = 'EV_TRANSFER--|--Home'
export const EVENT_FROM_REGISTRY = 'EVENT_FROM_REGISTRY--|--Home'
export const EVENT_FACEOFF= 'EVENT_FACEOFF--|--Home'
export const EVENT_WHITELIST = 'EVENT_WHITELIST--|--Home'

export const NEW_ITEM = 'NEW_ITEM--|--Home'
export const CHANGE_ITEM = 'CHANGE_ITEM--|--Home'
export const CHANGE_ITEMS = 'CHANGE_ITEMS--|--Home'

// UDapp
export const UDAPP_ERROR = 'UDAPP_ERROR--|--UDapp'
export const SET_ADDRESS = 'SET_ADDRESS--|--UDapp'
export const SET_FROM_ADDRESS = 'SET_FROM_ADDRESS--|--UDapp'
export const SET_ABI = 'SET_ABI--|--UDapp'
export const REFRESH_ETH_STORE = 'REFRESH_ETH_STORE--|--UDapp'
export const EXECUTE_METH = 'EXECUTE_METH--|--UDapp'