const SETUP_ETHEREUM_START = 'home/SETUP_ETHEREUM_START'

const SET_ABIS = 'home/SET_ABIS'
const SETUP_ETHEREUM_SUCCEEDED = 'home/SETUP_ETHEREUM_SUCCEEDED'
const SETUP_ETHEREUM_FAILED = 'home/SETUP_ETHEREUM_FAILED'
const SET_REGISTRY_CONTRACT = 'home/SET_REGISTRY_CONTRACT'
const SET_CONTRACTS = 'home/SET_CONTRACTS'
const CHOOSE_TCR = 'home/CHOOSE_TCR'

const POLL_LOGS_START = 'home/POLL_LOGS_START'

const UPDATE_BALANCES_START = 'home/UPDATE_BALANCES_START'
const UPDATE_BALANCES_SUCCEEDED = 'home/UPDATE_BALANCES_SUCCEEDED'
const UPDATE_BALANCES_FAILED = 'home/UPDATE_BALANCES_FAILED'

export default {
  SETUP_ETHEREUM_START,
  SET_ABIS,
  SETUP_ETHEREUM_SUCCEEDED,
  SETUP_ETHEREUM_FAILED,
  SET_REGISTRY_CONTRACT,
  SET_CONTRACTS,
  CHOOSE_TCR,
  POLL_LOGS_START,
  UPDATE_BALANCES_START,
  UPDATE_BALANCES_SUCCEEDED,
  UPDATE_BALANCES_FAILED,
}
