const SETUP_ETHEREUM_REQUEST = 'home--SETUP_ETHEREUM_REQUEST'

const SET_ABIS = 'home--SET_ABIS'
const SET_WALLET = 'home--SET_WALLET'
const SET_REGISTRY_CONTRACT = 'home--SET_REGISTRY_CONTRACT'
const SET_CONTRACTS = 'home--SET_CONTRACTS'
const CHOOSE_TCR = 'home--CHOOSE_TCR'

const POLL_LOGS_REQUEST = 'home--POLL_LOGS_REQUEST'

const UPDATE_BALANCES_REQUEST = 'home--UPDATE_BALANCES_REQUEST'
const UPDATE_BALANCES = 'home--UPDATE_BALANCES'

export default {
  SETUP_ETHEREUM_REQUEST,
  SET_ABIS,
  SET_WALLET,
  SET_REGISTRY_CONTRACT,
  SET_CONTRACTS,
  CHOOSE_TCR,
  POLL_LOGS_REQUEST,
  UPDATE_BALANCES_REQUEST,
  UPDATE_BALANCES,
}
