const SETUP_ETHEREUM_START = 'home/SETUP_ETHEREUM_START'
const SETUP_ETHEREUM_SUCCEEDED = 'home/SETUP_ETHEREUM_SUCCEEDED'
const SETUP_ETHEREUM_FAILED = 'home/SETUP_ETHEREUM_FAILED'

export default {
  SETUP_ETHEREUM_START,
  SETUP_ETHEREUM_SUCCEEDED,
  SETUP_ETHEREUM_FAILED,
}
