const SET_LISTINGS = 'listings/SET_LISTINGS'
const UPDATE_LISTING = 'listings/UPDATE_LISTING'
const DELETE_KEY = 'listings/DELETE_KEY'
const OPEN_SIDE_PANEL = 'listings/OPEN_SIDE_PANEL'

export { SET_LISTINGS, UPDATE_LISTING, DELETE_KEY, OPEN_SIDE_PANEL }
