const SEND_TRANSACTION = 'tx--SEND_TRANSACTION'

const TXN_MINING = 'tx--TXN_MINING'
const TXN_MINED = 'tx--TXN_MINED'
const CLEAR_TXN = 'tx--CLEAR_TXN'

const TX_APPROVE = 'tx--TX_APPROVE'
const TX_APPLY = 'tx--TX_APPLY'
const TX_CHALLENGE = 'tx--TX_CHALLENGE'

const TX_UPDATE_STATUS = 'tx--TX_UPDATE_STATUS'

const TX_REQUEST_VOTING_RIGHTS = 'tx--TX_REQUEST_VOTING_RIGHTS'
const TX_COMMIT_VOTE = 'tx--TX_COMMIT_VOTE'
const TX_REVEAL_VOTE = 'tx--TX_REVEAL_VOTE'

export default {
  SEND_TRANSACTION,
  TXN_MINING,
  TXN_MINED,
  CLEAR_TXN,
  TX_APPROVE,
  TX_APPLY,
  TX_CHALLENGE,
  TX_UPDATE_STATUS,
  TX_REQUEST_VOTING_RIGHTS,
  TX_COMMIT_VOTE,
  TX_REVEAL_VOTE,
}
