const SEND_TRANSACTION_START = 'tx/SEND_TRANSACTION_START'
const SEND_TRANSACTION_SUCCEEDED = 'tx/SEND_TRANSACTION_SUCCEEDED'
const SEND_TRANSACTION_FAILED = 'tx/SEND_TRANSACTION_FAILED'
const TXN_MINING = 'tx/TXN_MINING'
const CLEAR_TXN = 'tx/CLEAR_TXN'
const TX_REQUEST_VOTING_RIGHTS = 'tx/TX_REQUEST_VOTING_RIGHTS'
const TX_COMMIT_VOTE = 'tx/TX_COMMIT_VOTE'
const TX_REVEAL_VOTE = 'tx/TX_REVEAL_VOTE'

export {
  SEND_TRANSACTION_START,
  SEND_TRANSACTION_SUCCEEDED,
  SEND_TRANSACTION_FAILED,
  TXN_MINING,
  CLEAR_TXN,
  TX_REQUEST_VOTING_RIGHTS,
  TX_COMMIT_VOTE,
  TX_REVEAL_VOTE,
}
