const SETUP_ETHEREUM_START = 'ethProv/SETUP_ETHEREUM_START'

const SET_ABIS = 'ethProv/SET_ABIS'
const SETUP_ETHEREUM_SUCCEEDED = 'ethProv/SETUP_ETHEREUM_SUCCEEDED'
const SET_REGISTRY_CONTRACT = 'ethProv/SET_REGISTRY_CONTRACT'
const SET_CONTRACTS = 'ethProv/SET_CONTRACTS'
const CHOOSE_TCR = 'ethProv/CHOOSE_TCR'

const POLL_LOGS_START = 'ethProv/POLL_LOGS_START'

const UPDATE_BALANCES_START = 'ethProv/UPDATE_BALANCES_START'
const UPDATE_BALANCES_SUCCEEDED = 'ethProv/UPDATE_BALANCES_SUCCEEDED'

export default {
  SETUP_ETHEREUM_START,
  SET_ABIS,
  SETUP_ETHEREUM_SUCCEEDED,
  SET_REGISTRY_CONTRACT,
  SET_CONTRACTS,
  CHOOSE_TCR,
  POLL_LOGS_START,
  UPDATE_BALANCES_START,
  UPDATE_BALANCES_SUCCEEDED,
}
