const SETUP_ETHEREUM_REQUEST = 'ethProv/SETUP_ETHEREUM_REQUEST'

const SET_ABIS = 'ethProv/SET_ABIS'
const SET_WALLET = 'ethProv/SET_WALLET'
const SET_REGISTRY_CONTRACT = 'ethProv/SET_REGISTRY_CONTRACT'
const SET_CONTRACTS = 'ethProv/SET_CONTRACTS'
const CHOOSE_TCR = 'ethProv/CHOOSE_TCR'

const POLL_LOGS_REQUEST = 'ethProv/POLL_LOGS_REQUEST'

const UPDATE_BALANCES_REQUEST = 'ethProv/UPDATE_BALANCES_REQUEST'
const UPDATE_BALANCES = 'ethProv/UPDATE_BALANCES'

export default {
  SETUP_ETHEREUM_REQUEST,
  SET_ABIS,
  SET_WALLET,
  SET_REGISTRY_CONTRACT,
  SET_CONTRACTS,
  CHOOSE_TCR,
  POLL_LOGS_REQUEST,
  UPDATE_BALANCES_REQUEST,
  UPDATE_BALANCES,
}
