const SET_LISTINGS = 'listings/SET_LISTINGS'
const UPDATE_ONE_LISTING = 'listings/UPDATE_ONE_LISTING'
const DELETE_KEY = 'listings/DELETE_KEY'

export { SET_LISTINGS, UPDATE_ONE_LISTING, DELETE_KEY }
