const SET_ALL_LISTINGS = 'listings/SET_ALL_LISTINGS'
const UPDATE_ONE_LISTING = 'listings/UPDATE_ONE_LISTING'
const DELETE_ONE_LISTING = 'listings/DELETE_ONE_LISTING'

export { SET_ALL_LISTINGS, UPDATE_ONE_LISTING, DELETE_ONE_LISTING }
