export const SHOW_NOTIFICATION_START = 'notifications/SHOW_NOTIFICATION_START'
export const SHOW_NOTIFICATION_SUCCEEDED = 'notifications/SHOW_NOTIFICATION_SUCCEEDED'
export const SHOW_NOTIFICATION_FAILED = 'notifications/SHOW_NOTIFICATION_FAILED'
