export default {
  home: {
    name: 'Home',
    heading: 'Home methods',
    default: 'login',
    args: ['spender', 'owner', 'amount'],
    actions: ['approve', 'allowance', 'balanceOf', 'transfer'],
  },
  apply: {
    name: 'Apply',
    heading: 'Apply',
    default: 'Apply for a listing in the Registry.',
    args: ['listingHash', 'deposit', 'data'],
    actions: ['apply', 'appWasMade', 'deposit', 'approve', 'allowance'],
  },
  challenge: {
    name: 'Challenge',
    heading: 'Challenge',
    default: 'Challenge a listing. min_deposit will be transferred from your account.',
    args: ['listingHash'],
    actions: ['appWasMade', 'challenge', 'deposit', 'approve', 'allowance', 'requestVotingRights', 'withdrawVotingRights', 'updateStatus'],
  },
  commit_vote: {
    name: 'Commit vote',
    heading: 'Commit voting',
    default: 'Commit your secret vote',
    args: ['pollID', 'secretHash', 'numTokens'],
    actions: ['requestVotingRights', 'withdrawVotingRights', 'commitVote', 'rescueTokens'],
  },
  reveal_vote: {
    name: 'Reveal vote',
    heading: 'Reveal voting',
    default: 'Reveal your committed vote',
    args: ['pollID', 'salt'],
    actions: ['revealVote', 'rescueTokens'],
  },
  activities: {
    name: 'Activities',
    heading: 'Your current activities',
    default: 'Your current activities',
    actions: ['requestVotingRights', 'withdrawVotingRights', 'canBeWhitelisted', 'isWhitelisted', 'commitVote', 'revealVote', 'rescueTokens'],
  },
  search: {
    name: 'Search',
    heading: 'Search modal heading',
    default: 'Type the name of a listing to check its registry status',
    args: ['listingHash'],
    actions: ['appWasMade', 'isWhitelisted', 'canBeWhitelisted'],
  },
}