const SEND_TRANSACTION_START = 'app/tx/SEND_TRANSACTION_START'
const SEND_TRANSACTION_SUCCEEDED = 'app/tx/SEND_TRANSACTION_SUCCEEDED'
const SEND_TRANSACTION_PENDING = 'app/tx/SEND_TRANSACTION_PENDING'
const SEND_TRANSACTION_FAILED = 'tx/SEND_TRANSACTION_FAILED'
const TXN_MINING = 'tx/TXN_MINING'
const CLEAR_TXN = 'tx/CLEAR_TXN'
const OPEN_SIDE_PANEL = 'tx/OPEN_SIDE_PANEL'

export {
  SEND_TRANSACTION_START,
  SEND_TRANSACTION_SUCCEEDED,
  SEND_TRANSACTION_PENDING,
  SEND_TRANSACTION_FAILED,
  TXN_MINING,
  CLEAR_TXN,
  OPEN_SIDE_PANEL,
}
