const SEND_TRANSACTION_START = 'tx/SEND_TRANSACTION_START'
const SEND_TRANSACTION_SUCCEEDED = 'tx/SEND_TRANSACTION_SUCCEEDED'
const SEND_TRANSACTION_FAILED = 'tx/SEND_TRANSACTION_FAILED'
const TXN_MINING = 'tx/TXN_MINING'
const CLEAR_TXN = 'tx/CLEAR_TXN'

export {
  SEND_TRANSACTION_START,
  SEND_TRANSACTION_SUCCEEDED,
  SEND_TRANSACTION_FAILED,
  TXN_MINING,
  CLEAR_TXN,
}
