export const SETUP_ETHEREUM_START = 'home/SETUP_ETHEREUM_START'
export const SETUP_ETHEREUM_SUCCEEDED = 'home/SETUP_ETHEREUM_SUCCEEDED'
export const SETUP_ETHEREUM_FAILED = 'home/SETUP_ETHEREUM_FAILED'

export const SET_ABIS = 'ethProv/SET_ABIS'
export const SET_REGISTRY_CONTRACT = 'ethProv/SET_REGISTRY_CONTRACT'
export const SET_CONTRACTS = 'ethProv/SET_CONTRACTS'
export const CHOOSE_TCR = 'ethProv/CHOOSE_TCR'

export const UPDATE_BALANCES_START = 'ethProv/UPDATE_BALANCES_START'
export const UPDATE_BALANCES_SUCCEEDED = 'ethProv/UPDATE_BALANCES_SUCCEEDED'
export const UPDATE_BALANCES_FAILED = 'ethProv/UPDATE_BALANCES_FAILED'
