const SET_ABIS = 'ethProv/SET_ABIS'
const SET_REGISTRY_CONTRACT = 'ethProv/SET_REGISTRY_CONTRACT'
const SET_CONTRACTS = 'ethProv/SET_CONTRACTS'
const CHOOSE_TCR = 'ethProv/CHOOSE_TCR'

const UPDATE_BALANCES_START = 'ethProv/UPDATE_BALANCES_START'
const UPDATE_BALANCES_SUCCEEDED = 'ethProv/UPDATE_BALANCES_SUCCEEDED'
const UPDATE_BALANCES_FAILED = 'ethProv/UPDATE_BALANCES_FAILED'

export {
  SET_ABIS,
  SET_REGISTRY_CONTRACT,
  SET_CONTRACTS,
  CHOOSE_TCR,
  UPDATE_BALANCES_START,
  UPDATE_BALANCES_SUCCEEDED,
  UPDATE_BALANCES_FAILED,
}
