export const GET_ETHEREUM = 'GET_ETHEREUM--|--Home'
export const CHECK_PROVIDER = 'CHECK_PROVIDER--|--Home'
export const CHANGE_DOMAIN = 'CHANGE_DOMAIN--|--Home'
export const CONTRACT_ERROR = 'CONTRACT_ERROR--|--Home'
export const LOGS_ERROR = 'LOGS_ERROR--|--Home'
export const GET_ACCOUNTS_ERROR = 'GET_ACCOUNTS_ERROR--|--Home'

export const SET_CONTRACTS = 'SET_CONTRACTS--|--Home'
export const SET_DECODED_LOGS = 'SET_DECODED_LOGS--|--Home'
export const SET_MIN_DEPOSIT = 'SET_MIN_DEPOSIT--|--Home'
export const SET_ETHJS = 'SET_ETHJS--|--Home'

export const GET_TOKENS_ALLOWED = 'GET_TOKENS_ALLOWED--|--Home'
export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST--|--Home'
export const RECEIVE_WEB3_INSTANCE = 'RECEIVE_WEB3_INSTANCE--|--Home'
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS--|--Home'
export const SET_TOKENS_ALLOWED = 'SET_TOKENS_ALLOWED--|--Home'

export const TX_APPLY = 'TX_APPLY--|--Home'
export const TX_CHALLENGE = 'TX_CHALLENGE--|--Home'
export const TX_APPROVE = 'TX_APPROVE--|--Home'

export const EV_APPLICATION = 'EV_APPLICATION--|--Home'
export const EVENT_FROM_REGISTRY = 'EVENT_FROM_REGISTRY--|--Home'
export const EVENT_VOTING_ITEM = 'EVENT_VOTING_ITEM--|--Home'
export const EVENT_WHITELIST = 'EVENT_WHITELIST--|--Home'
export const EV_TRANSFER = 'EV_TRANSFER--|--Home'
export const EV_CHALLENGE = 'EV_CHALLENGE--|--Home'

export const DEFAULT_ACTION = 'DEFAULT_ACTION--|--VFilter'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER--|--VFilter'
export const SET_METHOD_SIGNATURES = 'SET_METHOD_SIGNATURES--|--VFilter'
export const SET_NEW_BUILT_FILTER = 'SET_NEW_BUILT_FILTER--|--VFilter'
export const SET_STATUS_UPDATE = 'SET_STATUS_UPDATE--|--VFilter'
export const SET_LOGS = 'SET_LOGS--|--VFilter'
export const GET_NEW_LOGS = 'GET_NEW_LOGS--|--VFilter'
export const GET_CUSTOM = 'GET_CUSTOM--|--VFilter'
export const SET_CUSTOM_DOMAINS = 'SET_CUSTOM_DOMAINS--|--VFilter'
export const TX_UPDATE_STATUS = 'TX_UPDATE_STATUS--|--VFilter'