const actions = {
  voting: [
    'requestVotingRights',
    'withdrawVotingRights',
    'rescueTokens',
    'rescueTokens',
    'commitVote',
    'revealVote',
    'startPoll',
    'getLockedTokens',
    'getInsertPointForNumTokens',
    'getNumPassingTokens',
    'getNumTokens',
    'getTotalNumberOfTokensForWinningOption',
    'voteTokenBalance',
    'commitPeriodActive',
    'getCommitHash',
    'getLastNode',
    'hasBeenRevealed',
    'isExpired',
    'isPassed',
    'pollEnded',
    'pollExists',
    'pollMap',
    'revealPeriodActive',
    'validPosition',
  ],
  token: ['approve', 'transfer', 'allowance', 'balanceOf'],
  registry: [
    'apply',
    'deposit',
    'challenge',
    'appWasMade',
    'isWhitelisted',
    'canBeWhitelisted',
    'updateStatus',
    'challengeCanBeResolved',
    'voterReward',
    'updateStatus',
    'claimReward',
    'apply',
    'deposit',
    'appWasMade',
  ],
}

export default {
  apply: {
    name: 'Apply',
    heading: 'Apply',
    default: 'Apply for a listing in the Registry.',
    actions: ['apply'],
    warning: ['approve']
  },
  challenge: {
    name: 'Challenge',
    heading: 'Challenge',
    default: 'Challenge a listing. min_deposit will be transferred from your account.',
    actions: ['challenge'],
    warning: ['approve'],
  },
  commitVote: {
    name: 'Commit Vote',
    heading: 'Voting',
    default: 'Commit your secret vote',
    actions: ['commitVote'],
    warning: ['approve', 'requestVotingRights'],
  },
  revealVote: {
    name: 'Reveal Vote',
    heading: 'Voting',
    default: 'Reveal your secret vote',
    actions: ['revealVote'],
    warning: ['approve'],
  },
  vote: {
    name: 'Voting',
    heading: 'Voting',
    default: 'Commit and reveal your secret vote',
    actions: ['voterReward', 'canBeWhitelisted', 'determineReward', 'tokenClaims', 'challengeCanBeResolved', 'updateStatus', 'withdrawVotingRights', 'rescueTokens', 'commitVote', 'revealVote'],
    warning: ['requestVotingRights'],
  },
  search: {
    name: 'Search',
    heading: 'Search modal heading',
    default: 'Type the name of a listing to check its registry status',
    actions: ['isWhitelisted'],
  },
}
